name: RecipeRewriteShowcase

author: SchnTgaiSpock

description: Adds plants, mob drops, food, and more to the nether

main: io.github.schntgaispock.rrshowcase.RRShowcase

website: https://github.com/SchnTgaiSpock/RecipeRewriteShowcase

version: ${project.version}

api-version: 1.14

depend:
  - Slimefun
